main: com.thatgamerblue.subauth.plugin.SubAuthPlugin
name: SubAuth
version: 1.0
description: SubAuth for Twitch account linking

permissions:
  subauth.bypass:
    description: allow a user to bypass subauth
    default: op